name: Run API Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run API tests
        run: |
          cd api_tests
          mvn clean test
