name: Run E2E Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd e2e_tests
          npm install

      - name: Install Playwright Browsers
        run: |
          cd e2e_tests
          npx playwright install

      - name: Run E2E tests
        run: |
          cd e2e_tests
          npx playwright test --reporter=html